spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_sell?useSSL=false&characterEncoding=UTF-8
  jpa:
    show-sql: true
server:
  port: 8081
env: dev
